//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POAppAccess
    {
        public int Id { get; set; }
        public int EmployeeID { get; set; }
        public bool IsAdmin { get; set; }
        public string Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    }
}
