//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseOrder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public int PurchaseNumber { get; set; }
        public string Priority { get; set; }
        public string Terms { get; set; }
        public System.DateTime DateRequested { get; set; }
        public Nullable<System.DateTime> DateRequired { get; set; }
        public string Justification { get; set; }
        public string Manager { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public Nullable<int> Vendor { get; set; }
        public string ProductType { get; set; }
        public string BillingAddress { get; set; }
        public string ShippingAddress { get; set; }
        public string Comment { get; set; }
        public string SignedBy { get; set; }
        public System.DateTime OrderDate { get; set; }
    }
}
